# -*- coding: utf-8 -*-
#!/usr/bin/python

############
#
#
#    Create DATA BASE for Ilios
#
#
#    V. Picouet
#
############


import sqlite3

conn = sqlite3.connect('book.db')
conn.text_factory = str


cursor = conn.cursor()
cursor.execute("""
CREATE TABLE IF NOT EXISTS users(
     id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
     name, TEXT,
     titre TEXT,
     oeuvre_date TEXT,
     texte TEXT
)
""")


texte1 = {"name" : "Henry Miller","titre" : "Tropique du Cancer","oeuvre_date" : "roman publié en 1934", "texte" : "Grands Dieux !    Que suis-je devenu ?   Quel droit avez-vous, vous tous, d'encombrer ma vie, de me voler mon temps, de sonder mon âme, de sucer mes pensées, de m'avoir pour compagnon, pour confident, pour bureau d'information ?   Pour quoi me prenez-vous ?    Suis-je un amuseur stipendié, dont on exige tous les soirs qu'il joue une farce intellectuelle sous vos nez imbéciles ?   Suis-je un esclave, acheté et dûment payé, pour ramper sur le ventre devant ces fainéants que vous êtes, et étendre à vos pieds tout ce que je fais et tout ce que je sais ?   Suis-je une fille dans un bordel que l'on somme de rtrousser ses jupes ou d'ôter sa chemise devant le premier homme en veston qui se présente ? Je suis un homme qui voudrait vivre une vie héroïque et rendre le monde plus supportable à ses propres yeux.   Si, dans quelque moment de faiblesse, de détente, de besoin, je lâche de la vapeur - un peu de colère brûlante dont la chaleur tombe avec les mots - rêve passionné, enveloppé des langes de l'image - eh! bien, prenez ou laissez... mais ne m'embêtez pas ! Je suis un homme libre - et j'ai besoin de ma liberté.   J'ai besoin d'être seul.   J'ai besoin de méditer ma honte et mon désespoir dans la retraite; j'ai besoin du soleil et du pavé des rues, sans compagnons, sans conversation, face à face avec moi-même, avec la musique de mon coeur pour toute compagnie...   Que voulez-vous de moi ?   Quand j'ai quelque chose à dire, je l'imprime.   Quand j'ai quelque chose à donner, je le donne.   Votre curiosité qui fourre son nez partout me fait lever le coeur.   Vos compliments m'humilient.   Votre thé m'empoisonne.   Je ne dois rien à personne.   Je veux être responsable devant Dieu seul...   s'il existe !"}
texte2 = {"name" : "Rachid Boudjedra","titre" : "La répudiation","oeuvre_date" : "roman publié en 1969", "texte" : "Hôpital. Bégonias dans le jardin. Fenêtres ouvertes. Les infirmières à varices déambulent, se méfient des malades qui gloussent et des scorpions qui grouillent sous les lits. Elles ont peur, mais elles auraient mieux fait d'être apodes plutôt que d'énerver les patients avec le glissement furtif de leurs pas. A quoi rime ce va-et-vient doucereux ? L'agitation est d'autant plus vaine qu'elles ne craignent rien : au moindre incident, des hommes dissimulés derrière les portes interviendront et juguleront toute tentative de sédition. Titubation : un malade entre, il a l'air d'un anachorète qui a perdu sa transe; une fois couché, le nouveau venu perd de son intérêt et il ne nous reste plus qu'à chercher un nouveau pôle d'attraction. Les bégonias ? Ils ont l'air passif. Les scorpions ? Ils ne cessent de tourner en rond et le bruit qu'ils font en s'entrechoquant ne peut parvenir qu'à une oreille initée. Un plateau plein de fruits trône sur la petite table vissée à mon lit; elle est donc venue. Préciser l'heure de son arrivée ou de son départ est au-dessus de mes forces ; me souvenir de ce qu'elle m'a dit exige un effort qui me laissera fourbu toute la semaine, la peau moite ; impression d'avoir mué en utilisant un émollient que le médecin m'aurait donné en cachette car le règlement interdit de telles pratiques : changer de peau. Inutile de me rappeler l'heure de son arrivée, ni la couleur de sa robe ; je connais seulement son prénom : Céline, et le numéro très spécial de sa voiture. Elle vient me voir souvent et le médecin m'autorise à partir avec elle pendant le week-end ; nous retrouvons alors la chambre hideuse et la couverture effilochée et j'ai hâte de revenir à l'asile, bien que j'aie passé toute la nuit à répéter que je ne voulais pas y retourner. Dans le service où je suis, il n'y a pas de camisole de force et personne ne hurle ; seules les infirmières nous gâchent notre plaisir et notre bien-être ; elles sont laides et ont la manie de faire sécher leurs mouchoirs sur les rebords des fenêtres de la grande salle commune ; elles arborent aussi une nodosité qui donne à leurs viages un caractère inexpugnable et définitif. Effrayantes, bigles, simiesques haridelles ; elles se prennent pour des martyres parce qu'elles soignent des fous. L'une d'entre elles ressemble étrangement à Lella Aïcha, la belle-mère de ma défunte soeur ; elle évite de me regarder et j'en fais autant ; son fils s'est remarié depuis quelques temps (comment l'ai-je appris ? Je n'en sais rien ! ). Tremblements. Vibrations... Sueur, ma mère ! La ville nous parvenait comme une rumeur impalpable et démesurée ; l'été s'éternisait et venait de la mer ; nous ne savions plus que faire. Dis-moi, Céline, lentement, le nom de la ville où je suis et le nom de la mer qui la baigne... Les médecins refusent de me le dire, sous prétexte que je simule."}
texte3 = {"name" : "Cioran","titre" : "Sur les cimes du désespoir","oeuvre_date" : "Chapitre face au silence paru en 1933 ", "texte" : "En arriver à ne plus apprécier que le silence, c'est réaliser l'expression essentielle du fait de vivre en marge de la vie. Chez les grands solitaires et les fondateurs de religions, l'éloge du silence a des racines plus profondes qu'on ne l'imagine. Il faut pour cela que la présence des hommes vous ait exaspéré, que la complexité des problèmes vous ait dégoûté au point que vous ne vous intéressiez plus qu'au silence et à ses cris.La lassitude porte à un amour illimité du silence, car elle prive les mots de leur signification pour en faire des sonorités vides; les concepts se diluent, la puissance des expressions s'atténue, toute parole dite ou entendue repousse, stérile. Tout ce qui part vers l'extérieur, ou qui en vient, reste un murmure monocorde et lointain, incapable d'éveiller l'intérêt ou la curiosité. Il vous semble alors inutile de donner votre avis, de prendre position ou d'impressionner quiconque; les bruits auxquels vous avez renoncé s'ajoutent au tourment de votre âme. Au moment de la solution suprême, après avoir déployé une énergie folle à résoudre tous les problèms, et affronté le vertige des cimes, vous trouvez dans le silence la seule réalité, l'unique forme d'expression."}
texte4 = {"name" : "Gabriel García Márquez","titre" : "Douze contes vagabonds","oeuvre_date" : "nouvelle écrite en Décembre 1978", "texte" : "Pour Noël, les enfants redemandèrent un bateau à rames.\n'D'accord, dit le père, on l'achètera en rentrant à Cartagena.'\nTotó, qui avait neuf ans, et Joel, sept ens, étaient plus têtus que ne le croyaient leurs parents.\n'Non, s'écrièrent-ils en choeur. On le veut ici et tout de suite.' \n- Pour commencer, répondit la mère, ici la seule eau navigable est celle de la douche.' \nLes parents avaient raison. A Cartagena de Indias, ils possédaient une maison avec un jardin, une digue qui s'enfonçait dans les eaux de la baie et un abri pour deux grands yachts. En revanche, à Madrid, ils vivaient les uns sur les autres au cinquième étage du numéro 47 du paseo de la Castellana. Mais au bout du compte ni l'un ni l'autre n'eurent le coeur de le leur refuser car ils leur avaient promis un bateau avec des rames, un sextant et une boussole s'ils étaient les premiers de la classe, et ils l'avaient été. De sorte que le père acheta le tout sans rien dire à son épouse qui, des deux, se montrait la plus réticente à payer les dettes de jeu. C'était un magnifique bateau en aluminium avec un filet doré qui marquait la ligne de flottaison.\n'Le bateau est dans le garage, avoua le père pendant le déjeuner. Le problème c'est qu'il n'entre pas dans l'ascenseur, qu'il ne passe pas dans l'escalier, et que dans le garage il n'y a plus de place.'Mais le samedi après-midi, les enfants invitèrent des camarades pour qu'ils les aident à monter le bateau par l'escalier et ils parvinrent à le porter jusque dans la chambre de service.'Bravo, leur dit le père. Et maintenant ?'"}
texte5 = {"name" : "Toto","titre" : "Blabla","oeuvre_date" : "roman publiécfzefler", "texte" : "Grands Dieux !    Que suis-je devenu ?   Quel droit avez-vous, vous tous, d'encombrer ma vie, de me voler mon temps, de sonder mon âme, de sucer mes pensées, de m'avoir pour compagnon, pour confident, pour bureau d'information ?   Pour quoi me prenez-vous ?    Suis-je un amuseur stipendié, dont on exige tous les soirs qu'il joue une farce intellectuelle sous vos nez imbéciles ?   Suis-je un esclave, acheté et dûment payé, pour ramper sur le ventre devant ces fainéants que vous êtes, et étendre à vos pieds tout ce que je fais et tout ce que je sais ?   Suis-je une fille dans un bordel que l'on somme de rtrousser ses jupes ou d'ôter sa chemise devant le premier homme en veston qui se présente ? Je suis un homme qui voudrait vivre une vie héroïque et rendre le monde plus supportable à ses propres yeux.   Si, dans quelque moment de faiblesse, de détente, de besoin, je lâche de la vapeur - un peu de colère brûlante dont la chaleur tombe avec les mots - rêve passionné, enveloppé des langes de l'image - eh! bien, prenez ou laissez... mais ne m'embêtez pas ! Je suis un homme libre - et j'ai besoin de ma liberté.   J'ai besoin d'être seul.   J'ai besoin de méditer ma honte et mon désespoir dans la retraite; j'ai besoin du soleil et du pavé des rues, sans compagnons, sans conversation, face à face avec moi-même, avec la musique de mon coeur pour toute compagnie...   Que voulez-vous de moi ?   Quand j'ai quelque chose à dire, je l'imprime.   Quand j'ai quelque chose à donner, je le donne.   Votre curiosité qui fourre son nez partout me fait lever le coeur.   Vos compliments m'humilient.   Votre thé m'empoisonne.   Je ne dois rien à personne.   Je veux être responsable devant Dieu seul...   s'il existe !"}
texte6 = {"name" : "Tati","titre" : "Blabla","oeuvre_date" : "romaqsfczefller", "texte" : "Grands Dieux !    Que suis-je devenu ?   Quel droit avez-vous, vous tous, d'encombrer ma vie, de me voler mon temps, de sonder mon âme, de sucer mes pensées, de m'avoir pour compagnon, pour confident, pour bureau d'information ?   Pour quoi me prenez-vous ?    Suis-je un amuseur stipendié, dont on exige tous les soirs qu'il joue une farce intellectuelle sous vos nez imbéciles ?   Suis-je un esclave, acheté et dûment payé, pour ramper sur le ventre devant ces fainéants que vous êtes, et étendre à vos pieds tout ce que je fais et tout ce que je sais ?   Suis-je une fille dans un bordel que l'on somme de rtrousser ses jupes ou d'ôter sa chemise devant le premier homme en veston qui se présente ? Je suis un homme qui voudrait vivre une vie héroïque et rendre le monde plus supportable à ses propres yeux.   Si, dans quelque moment de faiblesse, de détente, de besoin, je lâche de la vapeur - un peu de colère brûlante dont la chaleur tombe avec les mots - rêve passionné, enveloppé des langes de l'image - eh! bien, prenez ou laissez... mais ne m'embêtez pas ! Je suis un homme libre - et j'ai besoin de ma liberté.   J'ai besoin d'être seul.   J'ai besoin de méditer ma honte et mon désespoir dans la retraite; j'ai besoin du soleil et du pavé des rues, sans compagnons, sans conversation, face à face avec moi-même, avec la musique de mon coeur pour toute compagnie...   Que voulez-vous de moi ?   Quand j'ai quelque chose à dire, je l'imprime.   Quand j'ai quelque chose à donner, je le donne.   Votre curiosité qui fourre son nez partout me fait lever le coeur.   Vos compliments m'humilient.   Votre thé m'empoisonne.   Je ne dois rien à personne.   Je veux être responsable devant Dieu seul...   s'il existe !"}
texte7 = {"name" : "Victor Hugo","titre" : "Les miserables","oeuvre_date" : "roman publié en 1934 par Henry Miller", "texte" : "Grands Dieux !    Que suis-je devenu ?   Quel droit avez-vous, vous tous, d'encombrer ma vie, de me voler mon temps, de sonder mon âme, de sucer mes pensées, de m'avoir pour compagnon, pour confident, pour bureau d'information ?   Pour quoi me prenez-vous ?    Suis-je un amuseur stipendié, dont on exige tous les soirs qu'il joue une farce intellectuelle sous vos nez imbéciles ?   Suis-je un esclave, acheté et dûment payé, pour ramper sur le ventre devant ces fainéants que vous êtes, et étendre à vos pieds tout ce que je fais et tout ce que je sais ?   Suis-je une fille dans un bordel que l'on somme de rtrousser ses jupes ou d'ôter sa chemise devant le premier homme en veston qui se présente ? Je suis un homme qui voudrait vivre une vie héroïque et rendre le monde plus supportable à ses propres yeux.   Si, dans quelque moment de faiblesse, de détente, de besoin, je lâche de la vapeur - un peu de colère brûlante dont la chaleur tombe avec les mots - rêve passionné, enveloppé des langes de l'image - eh! bien, prenez ou laissez... mais ne m'embêtez pas ! Je suis un homme libre - et j'ai besoin de ma liberté.   J'ai besoin d'être seul.   J'ai besoin de méditer ma honte et mon désespoir dans la retraite; j'ai besoin du soleil et du pavé des rues, sans compagnons, sans conversation, face à face avec moi-même, avec la musique de mon coeur pour toute compagnie...   Que voulez-vous de moi ?   Quand j'ai quelque chose à dire, je l'imprime.   Quand j'ai quelque chose à donner, je le donne.   Votre curiosité qui fourre son nez partout me fait lever le coeur.   Vos compliments m'humilient.   Votre thé m'empoisonne.   Je ne dois rien à personne.   Je veux être responsable devant Dieu seul...   s'il existe !"}
texte8 = {"name" : "Jean Jacque Goldman","titre" : "Chanson","oeuvre_date" : "roman publié en 1934 par Henry Miller", "texte" : "Grands Dieux !    Que suis-je devenu ?   Quel droit avez-vous, vous tous, d'encombrer ma vie, de me voler mon temps, de sonder mon âme, de sucer mes pensées, de m'avoir pour compagnon, pour confident, pour bureau d'information ?   Pour quoi me prenez-vous ?    Suis-je un amuseur stipendié, dont on exige tous les soirs qu'il joue une farce intellectuelle sous vos nez imbéciles ?   Suis-je un esclave, acheté et dûment payé, pour ramper sur le ventre devant ces fainéants que vous êtes, et étendre à vos pieds tout ce que je fais et tout ce que je sais ?   Suis-je une fille dans un bordel que l'on somme de rtrousser ses jupes ou d'ôter sa chemise devant le premier homme en veston qui se présente ? Je suis un homme qui voudrait vivre une vie héroïque et rendre le monde plus supportable à ses propres yeux.   Si, dans quelque moment de faiblesse, de détente, de besoin, je lâche de la vapeur - un peu de colère brûlante dont la chaleur tombe avec les mots - rêve passionné, enveloppé des langes de l'image - eh! bien, prenez ou laissez... mais ne m'embêtez pas ! Je suis un homme libre - et j'ai besoin de ma liberté.   J'ai besoin d'être seul.   J'ai besoin de méditer ma honte et mon désespoir dans la retraite; j'ai besoin du soleil et du pavé des rues, sans compagnons, sans conversation, face à face avec moi-même, avec la musique de mon coeur pour toute compagnie...   Que voulez-vous de moi ?   Quand j'ai quelque chose à dire, je l'imprime.   Quand j'ai quelque chose à donner, je le donne.   Votre curiosité qui fourre son nez partout me fait lever le coeur.   Vos compliments m'humilient.   Votre thé m'empoisonne.   Je ne dois rien à personne.   Je veux être responsable devant Dieu seul...   s'il existe !"}
texte9 = {"name" : "Casanova","titre" : "Exister","oeuvre_date" : "roman publié en 1934 par Henry Miller", "texte" : "Grands Dieux !    Que suis-je devenu ?   Quel droit avez-vous, vous tous, d'encombrer ma vie, de me voler mon temps, de sonder mon âme, de sucer mes pensées, de m'avoir pour compagnon, pour confident, pour bureau d'information ?   Pour quoi me prenez-vous ?    Suis-je un amuseur stipendié, dont on exige tous les soirs qu'il joue une farce intellectuelle sous vos nez imbéciles ?   Suis-je un esclave, acheté et dûment payé, pour ramper sur le ventre devant ces fainéants que vous êtes, et étendre à vos pieds tout ce que je fais et tout ce que je sais ?   Suis-je une fille dans un bordel que l'on somme de rtrousser ses jupes ou d'ôter sa chemise devant le premier homme en veston qui se présente ? Je suis un homme qui voudrait vivre une vie héroïque et rendre le monde plus supportable à ses propres yeux.   Si, dans quelque moment de faiblesse, de détente, de besoin, je lâche de la vapeur - un peu de colère brûlante dont la chaleur tombe avec les mots - rêve passionné, enveloppé des langes de l'image - eh! bien, prenez ou laissez... mais ne m'embêtez pas ! Je suis un homme libre - et j'ai besoin de ma liberté.   J'ai besoin d'être seul.   J'ai besoin de méditer ma honte et mon désespoir dans la retraite; j'ai besoin du soleil et du pavé des rues, sans compagnons, sans conversation, face à face avec moi-même, avec la musique de mon coeur pour toute compagnie...   Que voulez-vous de moi ?   Quand j'ai quelque chose à dire, je l'imprime.   Quand j'ai quelque chose à donner, je le donne.   Votre curiosité qui fourre son nez partout me fait lever le coeur.   Vos compliments m'humilient.   Votre thé m'empoisonne.   Je ne dois rien à personne.   Je veux être responsable devant Dieu seul...   s'il existe !"}
texte10 = {"name" : "Vincent","titre" : "Livre1","oeuvre_date" : "roman publié en 1934 par Henry Miller", "texte" : "Grands Dieux !    Que suis-je devenu ?   Quel droit avez-vous, vous tous, d'encombrer ma vie, de me voler mon temps, de sonder mon âme, de sucer mes pensées, de m'avoir pour compagnon, pour confident, pour bureau d'information ?   Pour quoi me prenez-vous ?    Suis-je un amuseur stipendié, dont on exige tous les soirs qu'il joue une farce intellectuelle sous vos nez imbéciles ?   Suis-je un esclave, acheté et dûment payé, pour ramper sur le ventre devant ces fainéants que vous êtes, et étendre à vos pieds tout ce que je fais et tout ce que je sais ?   Suis-je une fille dans un bordel que l'on somme de rtrousser ses jupes ou d'ôter sa chemise devant le premier homme en veston qui se présente ? Je suis un homme qui voudrait vivre une vie héroïque et rendre le monde plus supportable à ses propres yeux.   Si, dans quelque moment de faiblesse, de détente, de besoin, je lâche de la vapeur - un peu de colère brûlante dont la chaleur tombe avec les mots - rêve passionné, enveloppé des langes de l'image - eh! bien, prenez ou laissez... mais ne m'embêtez pas ! Je suis un homme libre - et j'ai besoin de ma liberté.   J'ai besoin d'être seul.   J'ai besoin de méditer ma honte et mon désespoir dans la retraite; j'ai besoin du soleil et du pavé des rues, sans compagnons, sans conversation, face à face avec moi-même, avec la musique de mon coeur pour toute compagnie...   Que voulez-vous de moi ?   Quand j'ai quelque chose à dire, je l'imprime.   Quand j'ai quelque chose à donner, je le donne.   Votre curiosité qui fourre son nez partout me fait lever le coeur.   Vos compliments m'humilient.   Votre thé m'empoisonne.   Je ne dois rien à personne.   Je veux être responsable devant Dieu seul...   s'il existe !"}





textes = [texte1,texte2,texte3,texte4,texte5,texte6,texte7,texte8,texte9,texte10]


for un_texte in textes:
	cursor.execute("""
	INSERT INTO users(name, titre, oeuvre_date, texte) VALUES(:name, :titre, :oeuvre_date, :texte)""", un_texte)


cursor.execute("""SELECT id, name, titre, oeuvre_date, texte FROM users""")
rows = cursor.fetchall()
for row in rows:
    print('{0} : {1} - {2} - {3} - {4}'.format(row[0], row[1], row[2],row[3], row[4]))


conn.commit()
conn.close()

